### ISSUE TITLE
Imports failure

### ISSUE THREAD

**Issue by sloonz** [Grant-Zietsman/validate-typescript#4]
Documentation states : 

```javascript
import { ... } from 'validate-typescript/validators';  // imported above
import { ... } from 'validate-typescript/extensions';  // imported above
import { ... } from 'validate-typescript/assertions';  // not imported above
import { ... } from 'validate-typescript/conversions'; // not imported above
import { ... } from 'validate-typescript/errors';      // not imported above
```

However, I have to import `validate-typescript/lib/errors` after installing the library with `npm install validate-typescript`.

**Comment by Grant-Zietsman** [comment]
An attempt was made to modularize the imports as shown above. This required the `tsc` outputs be placed in the root directory which was not convenient for cleaning the repo. As a result, the lib output folder was added but the documentation was not updated.

I have subsequently, decided to avoid modular importing in the documentation but it will still work if you include the lib directory in the path as you mentioned above.
