### ISSUE TITLE
Validate exact model

### ISSUE THREAD

**Issue by ciforusalterra** [grant-zietsman/validate-typescript#8]
Hi there. How to validate input exactly with schema that we've defined? For example:
Schema:
{
  username: Type(String),
  password: Type(String)
}

User input:
{
  username: "uname",
  password: "pass",
  additional: "additional value not in schema"
}

I want validate-typescript raise exception that the user input did not match schema. Is it possible with this library?

**Comment by grant-zietsman** [comment]
Essentially this library just ensures that the provided object follows the schema and doesn't care about the additional fields. 😢

I am not actively maintaining this. It is was a component of a larger project that I no longer contributing to.

Here is an alternative:
See https://json-schema.org/ and https://www.npmjs.com/package/jsonschema
